language: generic

script: 
- rsync --version
- rsync -av -m --include='**/' --include='**/surefire-reports/**.xml' --include='**/surefire-reports/emailable-report.html' --exclude='*' --exclude='*.html' . /tmp/arch/
