language: java
jdk:
  - oraclejdk8

services:
- docker

before_install:
- whoami
- groups `whoami`
- sudo chown -R travis:travis /var/lib/docker

install:
- echo "skip 'gradle assemble' step"
- docker --version
- docker-compose --version

script: docker pull teradatalabs/centos6-java8-oracle:jdk1.8.0_92-80a011f

cache:
  directories:
   - docker


