language: java
jdk:
  - oraclejdk8

services:
- docker

before_install:
- ( test -e docker/cdh5-hive.tar && docker load -i docker/cdh5-hive.tar ) || true
- test -e docker/cdh5-hive.tar || ( echo 'FROM teradatalabs/cdh5-hive:4' > docker/Dockerfile && time docker build -t teradatalabs/cdh5-hive:4 docker && time docker save teradatalabs/cdh5-hive:4 > docker/cdh5-hive.tar )

install:
- echo "skip 'gradle assemble' step"

script: docker pull teradatalabs/cdh5-hive:4

cache:
  directories:
   - docker

