language: java

jdk:
  - oraclejdk8

install: echo "skip 'gradle assemble' step"
script: gradle build --continue --parallel

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/scripts

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/


