language: generic

install:
- echo "INSTALL"

script:
- echo 'It works on Travis!' > /tmp/mail.txt
- sudo apt-get install mailutils
- mail -v -s "Hello World" artur.gajowy@teradata.com < /tmp/mail.txt
- echo "SCRIPT"
