language: java
jdk:
  - oraclejdk8

services:
- docker

before_install:
- whoami
- groups `whoami`
- ( test -e docker/centos6-java8-oracle.tar && docker load -i docker/centos6-java8-oracle.tar ) || true
- test -e docker/centos6-java8-oracle.tar || ( echo 'FROM teradatalabs/centos6-java8-oracle:jdk1.8.0_92-80a011f' > docker/Dockerfile && docker build -t teradatalabs/centos6-java8-oracle:jdk1.8.0_92-80a011f docker && docker save teradatalabs/centos6-java8-oracle:jdk1.8.0_92-80a011f > docker/centos6-java8-oracle.tar )


install:
- echo "skip 'gradle assemble' step"
- docker --version
- docker-compose --version

script: docker pull teradatalabs/centos6-java8-oracle:jdk1.8.0_92-80a011f

cache:
  directories:
   - docker



