language: java

dist: trusty

jdk:
  - oraclejdk8

install:
- exit 1
- echo "skip 'gradle assemble' step"
- docker --version
- docker-compose --version

script: gradle build --continue --parallel

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/scripts

cache:
  directories:
   - $HOME/.gradle/caches/
   - $HOME/.gradle/wrapper/


